Repository luceroweb/guess-the-movie, pull requests merged in 2022-04, with the labels that each got.

#126 Xm 120 game over help
  Components/GameOverHelp.js
  Images/gameover.png
  Scenes/HowToPlay.js
Labels: Instructions

#127 feat(MainAnimation) add animation instruction text and arrow
  Components/HowToPlay/MainAnimation.js
  Images/main.png
  Scenes/HowToPlay.js
Labels: help wanted, Instructions

#128 El 121 correct answer instruction scene
  Components/HowToPlay/CorrectAnswerDemo.js
  Images/correctAnswerDemo.png
  Scenes/HowToPlay.js
Labels: Instructions

#135 feat(mainAnimation): add web picture and edit animation #130
  Components/HowToPlay/MainAnimation.js
  Images/mainWeb.png
  Scenes/HowToPlay.js
Labels: help wanted, Instructions

#136 El 132 correct answer scene mobile web
  Components/HowToPlay/CorrectAnswerDemo.js
  Images/correctAnswerDemoMobile.png
  Scenes/HowToPlay.js
Labels: Instructions

#134 refactor(game over animation): add conditional styles based on platfo…
  Components/GameOverHelp.js
  Images/gameOverMobile.png
  Scenes/HowToPlay.js
Labels: Instructions

#138 bug(lives text): correct sentence structure lives vs life #125
  Scenes/WrongAnswer.js
Labels: bug, minor(bug)

#141 Hsf 124 incorrect answer bug
  Components/TrueFalse.js
  Scenes/GameOver.js
Labels: bug, Game Over

#140 Hb 130 main scene mobile web animations
  Components/HowToPlay/MainAnimation.js
  Images/mainAnimation.png
  Images/mainAnimationWeb.png
  Images/mainWeb.png
  Scenes/HowToPlay.js
Labels: help wanted, Instructions

#139 Ml2 question page instructions 122
  Components/QuestionInstructions.js
  Images/question-answered.png
  Images/question-page.png
  Scenes/HowToPlay.js
Labels: Instructions

#149 Gsh question mobile animation 131
  Components/QuestionInstructions.js
  Images/HowToPlay/Questions/question-answered-mobile.png
  Images/HowToPlay/Questions/question-answered.png
  Images/HowToPlay/Questions/question-page-mobile.png
  Images/HowToPlay/Questions/question-page.png
Labels: Instructions

#150 Tw 137 wrong answer animation
  Components/HowToPlay/WrongAnswerHelp.js
  Images/WrongAnswerScreen.png
  Images/WrongAnswerScreenMobile.png
  Scenes/HowToPlay.js
Labels: Instructions

#151 feat(lives icons): display the number of lives with separate icons fo…
  Components/Lives.js
  Components/MultipleChoice.js
Labels: Question Construction, Lives Badge

#161 Hsf 146 lose game animation
  Components/HowToPlay/LoseGameInstruction.js
  Images/gameOverAnimationMobile.png
  Images/gameOverAnimationWEb.png
  Images/oneLifeAnimationMobile.png
  Images/oneLifeAnimationWeb.png
  Scenes/HowToPlay.js
Labels: Instructions

#165 Js 147 game over space
  Components/GamePlayMode.js
  Scenes/GameOver.js
Labels: bug, Game Over

#164 feat(Question.js) : move live icon below the movie-drive in screen & …
  Components/Lives.js
  Scenes/Question.js
  Scenes/WrongAnswer.js
Labels: bug, minor(bug)

#166 El 160 question scene multiple clicks
  Components/MultipleChoice.js
  Components/TrueFalse.js
Labels: bug, major(bug)

#169 refactor(game over): remove aspect ratio from milkywaybg styles
  Scenes/GameOver.js
Labels: bug, Game Over

#167 Ajm 156 state update sound bug
  Components/Clock.js
  Components/Timer.js
  Scenes/Question.js
Labels: bug, Correct Answer

#158 Gsh 142 settings modal bug
  Components/Nav.js
  Components/SettingsModal.js
  Utils/reducer.js
Labels: bug

#170 feat(lose game instruction): change life pop corn icon fade time #146
  Components/HowToPlay/LoseGameInstruction.js
Labels: Instructions

#171 Tw 148 bug display mode
  App.js
  Components/GamePlayMode.js
  Components/Nav.js
  package-lock.json
  package.json
Labels: bug

#172 feat(wrong-answer) : delete footer from wrong answer scene
  Components/Nav.js
Labels: bug, WrongAnswer

#174 Xm 173 share score
  Components/MultipleChoice.js
  Components/TrueFalse.js
  Scenes/GameOver.js
Labels: enhancement, Game Over

#176 feat(image): add mobile imageGame Title #162
  Images/theater-sign-generator-mobile.jpg
Labels: bug

#177 feat(app json): change name and slug value #162
  app.json
Labels: bug

#180 feature(correctanswer): Added lives to the correct answer page in eas…
  Components/Lives.js
  Scenes/CorrectAnswer.js
Labels: Lives Badge, Correct Answer

#181 GSH 23 modal genre selection
  Components/SettingsModal.js
  Utils/FetchApi.js
  Utils/reducer.js
Labels: Settings

#188 Js 163 bug question construction
  Components/GenerateQuestion.js
  Utils/madLibsArray.js
Labels: bug

#187 feat(game intruction setting): add game setting instruction GIF on ho…
  Components/HowToPlay/GameInstructionSetting.js
  Images/gameSettingsAnimation.gif
  Scenes/HowToPlay.js
Labels: Instructions

#191 Gsh 24 genre gameplay query
  Components/SettingsModal.js
  Utils/FetchApi.js
Labels: question, Feature Suggestion

#193 fix(settings modal): add the word settings to the top 186
  Components/SettingsModal.js
Labels: bug

#190 Ga 21 intro animation
  Components/Main.js
  Images/IntroAnimation/clapper2-closed.png
  Images/IntroAnimation/clapper2-no-arm-arial.png
  Images/IntroAnimation/clapper2-open.png
  Images/marquee.jpeg
  Images/openClapboard.png
  Images/theater-sign-generator-trimmed.png
  Images/theater-sign-generator.jpg
  Sounds/clapper.wav
Labels: Home Screen

#196 Applying the Theater.js template
  Scenes/GameOver.js
Labels: Game Over

#199 fix(game over): remove marginBottom from the Game Over text
  Scenes/GameOver.js
Labels: bug, Game Over

#198 GSH 194 reset winningstreak bug
  Components/MultipleChoice.js
  Components/TrueFalse.js
  Scenes/Question.js
  Scenes/WrongAnswer.js
Labels: bug, Winning Streak Badge, WrongAnswer

#206 fix(wrong answer): fix the text size for small screens #204
  Scenes/WrongAnswer.js
Labels: bug, minor(bug), WrongAnswer

#209 fix(Correct answer): remove top margin from next question button
  Scenes/CorrectAnswer.js
Labels: bug, minor(bug)

#213 fix(main scene): realign text in image and trim it to be center on the marquee
  Images/marqueeBackground.png
Labels: bug, Home Screen, minor(bug)

#215 fix(wrong answer): remove the gear icon from wrong answer scene #210
  Components/SettingsModal.js
Labels: bug, minor(bug), WrongAnswer

#214 Sr 201 main layout
  Components/Main.js
Labels: enhancement, minor(bug)

#219 fix(ios footer): add conditional space between | and A also | and H in the footer
  Layout/Footer.js
Labels: bug, minor(bug)

#217 Ajm 200 randomcast undefined bug
  Components/GenerateQuestion.js
Labels: bug, Question Construction

#220 bug(setTimout): Add setTimeout to useEffect for sound #208
  Scenes/Main.js
Labels: bug

#221 chore(images): add bak imgs and fix typo on clapper
  Images/Main/IntroAnimation/clapper2-no-arm-arial-revised.png
  Images/Main/IntroAnimation/clapper2-no-arm-arial.png
  Images/_bak/clapper2-no-arm-arial-revised.psd
  Scenes/Main.js
Labels: bug, minor(bug)
