Repository luceroweb/guess-the-movie, pull requests merged in 2022-03, with the labels that each got.

#62 Xm 40 genre #40
  Components/GenerateQuestion.js
  Components/Trailer.js
  Scenes/Question.js
  Utils/FetchApi.js
  Utils/madLibsArray.js
Labels: Question Construction

#66 refactor(generateQuestion): movie set name and genre #40
  Components/GenerateQuestion.js
Labels: Question Construction

#64 Fix footer on mobile #59
  Components/Footer.js
Labels: bug, Home Screen

#68 fix(edit footer)delete borderBottomWidth59
  Components/Footer.js
Labels: bug, help wanted, Home Screen

#72 Tw 58 badge position #58
  Scenes/Question.js
Labels: Question Construction, Winning Streak Badge

#73 fix(developerCredit): delete border style #65
  Scenes/DeveloperCredits.js
Labels: bug, help wanted, minor(bug)

#82 fix(about page):delete display and edit textDecoration
  Scenes/About.js
Labels: bug, help wanted

#63 fix(postMessage): Add window checking to Trailer component #47
  Components/Trailer.js
  package-lock.json
Labels: minor(bug)

#83 feat(lives): add state and reducer for lives #80
  Utils/reducer.js
Labels: Settings

#84 feat(performer question): add performer false questions
  Utils/madLibsArray.js
Labels: Mad Libs

#86 Tw 57 badge position
  Components/Badge.js
  Components/Trailer.js
  Images/drive-in-movie-mobile-mini.jpg
  Scenes/CorrectAnswer.js
Labels: bug, Winning Streak Badge

#85 Hsf 74 easy mode disable timer
  Components/MultipleChoice.js
  Components/TrueFalse.js
  Components/getIcon.js
  Scenes/Question.js
Labels: help wanted, Question Construction, Settings

#79 Ga 54 game play mode redux state
  Components/GamePlayMode.js
  Components/Nav.js
  Components/Trailer.js
  Utils/reducer.js
Labels: Settings

#70 Sr 60 fix question ios
  Components/Clock.js
  Components/Timer.js
  Scenes/Question.js
Labels: major(bug)

#89 Xm 81 lives display
  Components/Lives.js
  Scenes/Question.js
Labels: Question Construction, Settings, Lives Badge

#90 Hsf 78 calculate lives
  Components/GenerateQuestion.js
  Components/MultipleChoice.js
  Components/TrueFalse.js
  Utils/reducer.js
Labels: Question Construction, Settings

#61 Ml2 settings modal 25
  Components/Header.js
  Components/SettingsModal.js
  package-lock.json
Labels: Settings

#96 Tw 87 bug mode indicator position
  Components/GamePlayMode.js
  Components/Nav.js
Labels: bug, minor(bug)

#99 Js 94 date format bug
  Utils/madLibsArray.js
Labels: bug, Question Construction

#101 feat(gamePlayMode):change the name of game play mode
  Components/GamePlayMode.js
  Utils/reducer.js
Labels: Question Construction

#105 chore(wrong answer): add wrong answer sound effect #103
  Scenes/WrongAnswer.js
  Sounds/wrongSound.wav
Labels: Answer Construction

#102 Ga 100 explanation text wrong answer
  Components/Badge.js
  Components/Clock.js
  Components/Footer.js
  Components/GamePlayMode.js
  Components/GenerateQuestion.js
  Components/Header.js
  Components/Lives.js
  Components/MultipleChoice.js
  Components/Nav.js
  Components/SettingsModal.js
  Components/Timer.js
  Components/Trailer.js
  Components/TrueFalse.js
  Components/getIcon.js
  Images/drive-in-movie-mobile-mini.jpg
  Scenes/About.js
  Scenes/CorrectAnswer.js
  Scenes/DeveloperCredits.js
  Scenes/Question.js
  Scenes/WrongAnswer.js
  Sounds/wrongSound.wav
  Utils/madLibsArray.js
  Utils/reducer.js
  package-lock.json
Labels: bug, enhancement, minor(bug)

#108 feat(madLibs): add questions using two casts #104
  Components/GenerateQuestion.js
  Utils/madLibsArray.js
Labels: enhancement, Question Construction

#114 Hsf 98 fix wrong answer scene container
  Scenes/WrongAnswer.js
Labels: bug, WrongAnswer

#115 Hb 111 display live single mode
  Scenes/Question.js
Labels: bug, help wanted

#116 style(isCorrect) : refactor multipleChoice & True/false scenes #112
  Components/MultipleChoice.js
  Components/TrueFalse.js
Labels: enhancement, Question Construction

#118 Ga 100 explanation text wrong answer
  Scenes/WrongAnswer.js
Labels: WrongAnswer

#92 Pja #2 settings gameplay
  Components/GamePlayMode.js
  Components/MultipleChoice.js
  Components/SettingsModal.js
  Components/TrueFalse.js
  Scenes/Question.js
  Utils/reducer.js
  package-lock.json
  package.json
Labels: enhancement
